"""Descriptive field-role maps for existing artifact families."""

from __future__ import annotations

from typing import Dict, List

from zk_offline_dqn.artifacts.schemas import (
    SCHEMA_FORWARD_TD_MLP_V1,
    SCHEMA_MINIBATCH_TD_V1,
    SCHEMA_ONE_STEP_SGD_TINY_V1,
    SCHEMA_ONE_STEP_UPDATE_V1,
    SCHEMA_SHORT_TRACE_UPDATE_V2,
    SCHEMA_TD_MVP_BATCH_TEST_VECTOR_V1,
    SCHEMA_TD_MVP_TEST_VECTOR_V1,
)


FIELD_ROLES: Dict[str, Dict[str, List[str]]] = {
    SCHEMA_MINIBATCH_TD_V1: {
        "public": [
            "dataset_root",
            "batch_size",
            "batch_mode",
            "leaf_indices",
            "loss_type",
            "batch_loss_fp",
            "checkpoint_sha256",
            "checkpoint_commitment_type",
            "online_state_dict_key",
            "online_state_dict_sha256",
            "target_state_dict_sha256",
        ],
        "items": [
            "index",
            "transition",
            "leaf",
            "serialized_leaf",
            "leaf_hash",
            "merkle_path",
            "td_witness",
        ],
        "private": [],
        "steps": [],
        "notes": ["checkpoint_path", "source_dataset", "export_command"],
        "debug": [],
    },
    SCHEMA_ONE_STEP_UPDATE_V1: {
        "public": [
            "dataset_root",
            "batch_indices",
            "batch_size",
            "loss_type",
            "optimizer_type",
            "learning_rate_fp",
            "pre_checkpoint_sha256",
            "post_checkpoint_sha256",
            "checkpoint_commitment_type",
            "pre_online_state_dict_key",
            "pre_online_state_dict_sha256",
            "pre_target_state_dict_sha256",
            "post_online_state_dict_key",
            "post_online_state_dict_sha256",
            "post_target_state_dict_sha256",
        ],
        "items": [
            "index",
            "transition",
            "leaf",
            "leaf_hash",
            "merkle_path",
            "td_witness",
        ],
        "private": ["update_witness"],
        "steps": [],
        "notes": ["checkpoint_path", "post_checkpoint_path", "merkle_path"],
        "debug": [],
    },
    SCHEMA_SHORT_TRACE_UPDATE_V2: {
        "public": [
            "dataset_root",
            "trace_batch_indices",
            "num_steps",
            "batch_size",
            "loss_type",
            "optimizer_type",
            "learning_rate_fp",
            "sampling_rule_type",
            "start_offset",
            "sampling_seed",
            "dataset_size",
            "target_sync_every",
            "initial_checkpoint_sha256",
            "final_checkpoint_sha256",
            "checkpoint_commitment_type",
            "initial_online_state_dict_key",
            "initial_online_state_dict_sha256",
            "initial_target_state_dict_sha256",
            "final_online_state_dict_key",
            "final_online_state_dict_sha256",
            "final_target_state_dict_sha256",
        ],
        "items": [],
        "private": [],
        "steps": [
            "step_index",
            "input_checkpoint_sha256",
            "raw_output_checkpoint_sha256",
            "next_checkpoint_sha256",
            "target_sync_applied",
            "one_step_artifact",
            "sync_state_witness",
        ],
        "notes": [
            "merkle_path",
            "initial_checkpoint_path",
            "final_checkpoint_path",
        ],
        "debug": [],
    },
    SCHEMA_TD_MVP_TEST_VECTOR_V1: {
        "public": [
            "dataset_root",
            "fp_scale",
            "gamma_fp",
            "claimed_target_fp",
            "claimed_loss_fp",
            "leaf_index",
        ],
        "items": [],
        "private": [
            "transition",
            "leaf",
            "leaf_hash",
            "merkle_path",
            "td_witness",
        ],
        "steps": [],
        "notes": ["source"],
        "debug": [],
    },
    SCHEMA_TD_MVP_BATCH_TEST_VECTOR_V1: {
        "public": [
            "dataset_root",
            "fp_scale",
            "gamma_fp",
            "batch_size",
            "batch_mode",
            "leaf_indices",
            "claimed_batch_loss_fp",
            "batch_loss_fp",
        ],
        "items": [],
        "private": ["items"],
        "steps": [],
        "notes": ["source"],
        "debug": [],
    },
    SCHEMA_FORWARD_TD_MLP_V1: {
        "public": [
            "dataset_root",
            "fp_scale",
            "gamma_fp",
            "batch_size",
            "leaf_indices",
            "network_spec_hash",
            "network_layer_sizes",
            "online_model_commitment",
            "target_model_commitment",
            "claimed_item_losses_fp",
            "claimed_batch_loss_fp",
        ],
        "items": [],
        "private": ["online_model", "target_model", "items"],
        "steps": [],
        "notes": ["source", "statement", "relation"],
        "debug": [],
    },
    SCHEMA_ONE_STEP_SGD_TINY_V1: {
        "public": [
            "fp_scale",
            "gamma_fp",
            "learning_rate_fp",
            "optimizer_type",
            "batch_size",
            "network_spec_hash",
            "network_layer_sizes",
            "pre_model_commitment",
            "post_model_commitment",
            "target_model_commitment",
            "leaf_indices",
            "claimed_batch_loss_fp",
        ],
        "items": [],
        "private": [
            "online_model",
            "target_model",
            "post_online_model",
            "items",
            "update_witness",
        ],
        "steps": [],
        "notes": ["source", "statement", "relation"],
        "debug": [],
    },
}


def field_roles_for(schema_version: str) -> Dict[str, List[str]]:
    return {key: list(value) for key, value in FIELD_ROLES[schema_version].items()}
