"""Known SP1-related fixture paths and classifications.

This module is intentionally descriptive only. It does not create, move, or
rewrite any fixture files.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List


TD_MVP_SP1 = "td_mvp_sp1"
FORWARD_TD_MLP_PYTHON_SMOKE = "forward_td_mlp_python_smoke"
ONE_STEP_SGD_TINY_PYTHON_SMOKE = "one_step_sgd_tiny_python_smoke"


@dataclass(frozen=True)
class Sp1Fixture:
    path: Path
    purpose: str
    regression_critical: bool
    description: str


KNOWN_SP1_FIXTURES: tuple[Sp1Fixture, ...] = (
    Sp1Fixture(
        path=Path("zk_backend/test_vectors/td_mvp_case_0.json"),
        purpose=TD_MVP_SP1,
        regression_critical=True,
        description="Canonical single-transition TD MVP input used by SP1 host.",
    ),
    Sp1Fixture(
        path=Path(
            "artifacts/fixtures/forward_td_mlp/"
            "forward_td_mlp_batch_size_1.json"
        ),
        purpose=FORWARD_TD_MLP_PYTHON_SMOKE,
        regression_critical=True,
        description="Forward-TD MLP batch-1 fixture generated by Python smoke.",
    ),
    Sp1Fixture(
        path=Path(
            "artifacts/fixtures/one_step_sgd_tiny/"
            "one_step_sgd_tiny_valid.json"
        ),
        purpose=ONE_STEP_SGD_TINY_PYTHON_SMOKE,
        regression_critical=True,
        description="One-step SGD tiny valid fixture generated by Python smoke.",
    ),
)


def known_fixtures() -> List[Sp1Fixture]:
    return list(KNOWN_SP1_FIXTURES)


def fixture_paths() -> List[Path]:
    return [fixture.path for fixture in KNOWN_SP1_FIXTURES]


def fixtures_by_purpose(purpose: str) -> List[Sp1Fixture]:
    return [fixture for fixture in KNOWN_SP1_FIXTURES if fixture.purpose == purpose]


def regression_critical_fixtures() -> Iterable[Sp1Fixture]:
    return (fixture for fixture in KNOWN_SP1_FIXTURES if fixture.regression_critical)
