"""The paper's tables must be the generated ones, regenerated from the artifacts.

Both tables used to be hand-typed LaTeX, and they drifted a long way without
anything noticing: the paper reported 440.6 s for a fragment that proves in
3.8 s, listed MountainCar as a benchmark environment months after it was
dropped, and carried a Table 1 built from an experiment that no longer existed.
check_paper_claims stayed green throughout, because it checks the wording of
claims and not the agreement of numbers.

So these tests close that gap from both sides: the paper has to \\input the
generated files rather than restate them, and the generated files have to match
what the committed CSVs currently say.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from zk_offline_dqn.experiments.paper_tables import GENERATED, render_all, write_all

RESULTS = ROOT / "paper/sections/results.tex"
FINAL = ROOT / "artifacts/reports/final_ndss"


class GeneratedTablesAreCurrentTests(unittest.TestCase):
    def setUp(self) -> None:
        if not (FINAL / "table2_zk_proof_cost.csv").exists():
            self.skipTest("final_ndss tables not generated")

    def test_committed_tables_match_a_fresh_render(self) -> None:
        # Catches both a stale checkout and a hand edit of the generated file.
        with tempfile.TemporaryDirectory() as tmp:
            write_all(Path(tmp))
            for path in sorted(Path(tmp).iterdir()):
                with self.subTest(table=path.name):
                    committed = GENERATED / path.name
                    self.assertTrue(committed.exists(), f"{path.name} not committed")
                    self.assertEqual(
                        committed.read_text(encoding="utf-8"),
                        path.read_text(encoding="utf-8"),
                        f"{path.name} is stale; run "
                        "python -m zk_offline_dqn.experiments.paper_tables",
                    )

    def test_every_generated_table_says_it_is_generated(self) -> None:
        for name, text in render_all().items():
            with self.subTest(table=name):
                self.assertTrue(text.startswith("% Generated by"), name)


class PaperInputsTheGeneratedTablesTests(unittest.TestCase):
    def setUp(self) -> None:
        if not RESULTS.exists():
            self.skipTest("paper sources not present")
        self.text = RESULTS.read_text(encoding="utf-8")

    def test_results_inputs_both_tables(self) -> None:
        for name in ("table1_rl_performance", "table2_proof_cost"):
            with self.subTest(table=name):
                self.assertIn(rf"\input{{generated/{name}}}", self.text)

    def test_results_does_not_restate_the_numbers(self) -> None:
        # A tabular body in this file is a hand-typed table returning.
        self.assertNotIn(r"\toprule", self.text.split(r"\input{generated/")[0])

    def test_the_dropped_environment_is_gone_from_included_sections(self) -> None:
        main = (ROOT / "paper/main.tex").read_text(encoding="utf-8")
        for path in sorted((ROOT / "paper/sections").glob("*.tex")):
            if f"sections/{path.stem}" not in main:
                continue  # not \input by main.tex, so it is not part of the paper
            with self.subTest(section=path.name):
                self.assertNotIn("MountainCar", path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
